# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
from initialise import answer
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.__config__.show()

2.1.1
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.9/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.9/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.9/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.9/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
from sys import getsizeof
print(getsizeof(Z))
print("%d bytes" % (Z.size * Z.itemsize))


192
80 bytes


In [6]:
answer(4)

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
help (np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``o

In [8]:
answer(5)

%run `python -c "import numpy; numpy.info(numpy.add)"`


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
Z = np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
Z = np.arange(10, 50)

In [11]:
answer(7)

Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
# reverse Z
Z[40:0:-4]

array([49, 45, 41, 37, 33, 29, 25, 21, 17, 13])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
Z=np.arange(0,9)
Z=Z.reshape(3,3)
print(Z)
answer(9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
Z = np.array([1,2,0,0,4,0])
np.nonzero(Z)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [15]:
Z = np.identity(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [16]:
np.random.random((3,3,3))
answer(12)

Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [17]:
Z= np.random.random((10,10))
print(Z)
print(np.max(Z))
print(Z.min())
print(np.min(Z))
# answer(13)

[[0.29046683 0.14976219 0.93802996 0.91890268 0.97850171 0.49878789
  0.79444936 0.67247779 0.07434451 0.64169984]
 [0.75089011 0.49848522 0.39927461 0.28563381 0.56576875 0.08144644
  0.65534129 0.26142669 0.67458635 0.51675081]
 [0.64904966 0.55963229 0.27735229 0.33086822 0.35607765 0.36784311
  0.19742529 0.23286872 0.23827042 0.8879528 ]
 [0.9328471  0.74792742 0.89399336 0.59665858 0.86278868 0.20589919
  0.59349635 0.110205   0.37299664 0.92134581]
 [0.14487492 0.84794459 0.02869005 0.31002908 0.60079013 0.27126219
  0.05291175 0.63939965 0.65409876 0.08841746]
 [0.9994599  0.01258441 0.91026375 0.33792599 0.80887131 0.66154066
  0.33381372 0.99855694 0.56138699 0.57942352]
 [0.42594661 0.96906572 0.97013802 0.52576803 0.15028876 0.80786166
  0.30356343 0.3291431  0.15463081 0.58143891]
 [0.19103921 0.69500962 0.57566889 0.33946895 0.62754663 0.34069787
  0.43956771 0.21829873 0.3223896  0.86944565]
 [0.92721437 0.99363738 0.76673957 0.48627377 0.79233    0.23455279
  0.13874347

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
Z = np.random.random((30))
print(Z.mean())
answer(14)

0.47380695505405335
Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [20]:
answer(15)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [21]:
Z = np.random.random((10,10))
Z[0,:] = 0
Z[-1,:] = 0
Z[:,0] = 0
Z[:,-1] = 0
Z

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.54551477, 0.89274897, 0.26460855, 0.45757138,
        0.63067518, 0.31705748, 0.91647392, 0.9389207 , 0.        ],
       [0.        , 0.64193809, 0.48917289, 0.02920064, 0.17767415,
        0.52076881, 0.8137484 , 0.76296959, 0.73529516, 0.        ],
       [0.        , 0.25697416, 0.58419901, 0.60814934, 0.88767203,
        0.30928643, 0.68169916, 0.56129925, 0.02009428, 0.        ],
       [0.        , 0.04911591, 0.44306614, 0.68821232, 0.26151793,
        0.24090637, 0.54442373, 0.11514492, 0.95652425, 0.        ],
       [0.        , 0.75084105, 0.18460632, 0.53152588, 0.79041522,
        0.69922219, 0.42695116, 0.36241217, 0.20980704, 0.        ],
       [0.        , 0.91320995, 0.59906666, 0.08626956, 0.66549225,
        0.07997022, 0.84374089, 0.98294102, 0.82017624, 0.        ],
       [0.        , 0.36134321, 0.8102634

In [22]:
answer(16)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


In [23]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [24]:
answer(17)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [25]:
Z=np.zeros((5,5))
Z[1][0]=1
Z[2][1]=2
Z

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
Z = np.diag([1,2,3,4],k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [27]:
Z = np.zeros((8,8))
Z[::2,::2]=1
Z[1:,1:][::2,::2]=1
# Z[:1:2,::2]=0
# Z[:,::2]=1
Z

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [28]:
answer(19)

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [29]:
Z = np.arange(0,336).reshape((6,7,8))
Z[1,5,4]

np.int64(100)

In [30]:
answer(20)

print(np.unravel_index(99,(6,7,8)))


In [31]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [32]:
Z = np.tile(np.array(([0,1],[1,0])),(4,4))
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [33]:
answer(21)

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [34]:
Z=np.random.random((5,5))
Z = Z-Z.mean()/Z.std()
Z

array([[-1.87783414, -1.36529096, -1.3141015 , -1.0531396 , -1.67534967],
       [-1.89192965, -1.68857081, -1.64982186, -1.64404448, -1.48739906],
       [-1.48844382, -1.46179252, -1.81658588, -1.33746645, -1.52060689],
       [-1.29861825, -1.54130937, -1.63577712, -1.57958312, -1.76446357],
       [-1.8556053 , -1.45974423, -2.03773272, -1.23429915, -1.74623721]])

In [35]:
Z = (Z - np.mean (Z)) / (np.std (Z))
Z

array([[-1.30701879,  0.92002282,  1.14244516,  2.27634576, -0.42720739],
       [-1.36826492, -0.48465431, -0.31628701, -0.29118382,  0.38945325],
       [ 0.38491366,  0.50071571, -1.04089015,  1.04092254,  0.2451625 ],
       [ 1.20972111,  0.15520856, -0.25526146, -0.01109398, -0.81441451],
       [-1.21043267,  0.50961572, -2.0017911 ,  1.48919282, -0.7352195 ]])

In [36]:
answer(22)

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [37]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


In [38]:
np.dtype({'names':['R','G', 'B', 'A'], 'formats':[np.ubyte,np.ubyte,np.ubyte,np.ubyte]})

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [39]:
A= np.arange(15).reshape((5,3))
B= np.arange(6).reshape((3,2))
np.dot(A,B)
A.dot(B)


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [40]:
answer(24)

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [41]:
Z = np.arange(10)
Z[3:8]=-1*Z[3:8]
Z

array([ 0,  1,  2, -3, -4, -5, -6, -7,  8,  9])

In [42]:
answer(25)

# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [43]:
%load_ext autoreload
%autoreload 2

In [44]:
r = range(5)
for i in r:
    print(i)
    
np.sum(r)    

0
1
2
3
4


np.int64(10)

r = range(5)



In [45]:

print(sum(range(5), -1))

print(np.sum(range(5), -1))


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [46]:
Z = np.array([1,2,3])
# Z**Z
# (2 << Z) >> 2
# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [47]:
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_4349/4032259419.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [48]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-8.66543491  1.95704235  9.68897319 -2.55803866  6.12089915  8.74187537
  1.13955893  8.86366143 -7.65403438 -5.64643467]
[-9.  2. 10. -3.  7.  9.  2.  9. -8. -6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [49]:
A = np.array([1,2,3,4,5])
B = np.array([5,4,3,2,7])
C = np.intersect1d(A,B)
C


array([2, 3, 4, 5])

In [50]:
answer(30)

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [51]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [52]:
np.emath.sqrt(-1)


np.complex128(1j)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [53]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)


2024-09-23


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [54]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [55]:
A = np.arange(0.,9).reshape(3,3)
B = np.arange(9.,18).reshape(3,3)
#np.multiply(np.add(A,B), np.negative(np.divide(A,2)))
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
A


array([[  -0. ,   -5.5,  -13. ],
       [ -22.5,  -34. ,  -47.5],
       [ -63. ,  -80.5, -100. ]])

In [56]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [57]:
Z = np.random.random((1,5))
Z=Z*10
print(Z)
print(np.floor(Z))
print(np.trunc(Z))
print(np.astype(Z, int))
print(Z-Z%1)


[[9.26515777 8.81897866 7.49510201 5.41504466 8.02707187]]
[[9. 8. 7. 5. 8.]]
[[9. 8. 7. 5. 8.]]
[[9 8 7 5 8]]
[[9. 8. 7. 5. 8.]]


In [58]:
answer(36)

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [59]:
Z=np.zeros((5,5))
Z = Z+np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [60]:
answer(37)

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [61]:
np.fromiter(i in range (1,10), dtype=int)

TypeError: 'bool' object is not iterable

In [87]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [85]:
answer(38)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [97]:
Z=np.linspace(0,1, num=11, endpoint=False)
Z=Z[1:]
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [98]:
answer(39)

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [101]:
Z = np.random.random(10)
Z.sort()
Z

array([0.03136397, 0.04760837, 0.18813794, 0.36339801, 0.37967373,
       0.38624276, 0.43019989, 0.51538722, 0.94865745, 0.96256641])

In [102]:
answer(40)

Z = np.random.random(10)
Z.sort()
print(Z)


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [105]:
Z = np.arange(10)
np.add.reduce(Z)

np.int64(45)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [109]:
A=np.random.random(10)
B=np.random.random(10)
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [113]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [70]:
A = np.random.random((10,2))
print(A)
L = np.sqrt(A[:,0]**2+A[:,1]**2)
U = np.arctan2(A[:,1]/A[:,0])
B =  np.append(L,U).reshape(10,2)
B

answer(44)


[[0.82426892 0.65960707]
 [0.04069604 0.20374766]
 [0.47775471 0.52604597]
 [0.69114787 0.16368909]
 [0.83215523 0.00780929]
 [0.41335817 0.63575832]
 [0.49727902 0.09147748]
 [0.40656924 0.69674262]
 [0.64968106 0.11615141]
 [0.84032705 0.91337122]]
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [69]:
Z = np.random.random(10)
a = np.argmax(Z)
Z[a]=0
answer(45)


Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [72]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [78]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
# print(C)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [66]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [79]:
np.set_printoptions(threshold=float('inf'))
Z = np.zeros((40,40))
print(Z)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [89]:
Z=np.random.random(10)
c=0.5
res = np.argmin(np.abs(Z-c))
print(Z[res])

answer(50)

0.5086802868863255
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [96]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [104]:
Z = np.random.random((10,2))
print(Z)
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
#print(X)
#print(Y)
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# # Much faster with scipy
# import scipy
# # Thanks Gavin Heverly-Coulson (#issue 1)
# import scipy.spatial

# Z = np.random.random((10,2))
# D = scipy.spatial.distance.cdist(Z,Z)
# print(D)


[[5.76501583e-01 5.03611622e-01]
 [1.65725683e-02 7.69550313e-01]
 [9.35163535e-01 2.90804992e-01]
 [8.76797809e-01 6.64667526e-06]
 [9.72707609e-02 4.18620652e-01]
 [2.21864544e-01 4.96603830e-02]
 [4.05627350e-01 4.83159340e-01]
 [1.56243089e-01 6.30732718e-01]
 [6.74159042e-01 4.96895407e-01]
 [7.44257117e-01 7.52446483e-01]]
[[0.         0.61987409 0.41704323 0.58634102 0.486709   0.57605482
  0.17209387 0.43906375 0.09788813 0.30010116]
 [0.61987409 0.         1.03586024 1.15420315 0.36008863 0.74858954
  0.48309773 0.19692176 0.71187124 0.72788553]
 [0.41704323 1.03586024 0.         0.29659777 0.84758548 0.75295828
  0.56339042 0.84986347 0.33256068 0.49955793]
 [0.58634102 1.15420315 0.29659777 0.         0.88481642 0.65681282
  0.67486156 0.95760873 0.53661989 0.76402405]
 [0.486709   0.36008863 0.84758548 0.88481642 0.         0.38942944
  0.31503814 0.22015736 0.58217439 0.7280323 ]
 [0.57605482 0.74858954 0.75295828 0.65681282 0.38942944 0.
  0.4708398  0.58476596 0.63607349

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [110]:
Z=(np.random.random(10)*100).astype(np.float32)
Y=Z.view(np.int32)
Y[:]=Z
print(Y)
answer(53)

[42 27 57 54 20 33 36 47 61 68]
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [119]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.float16)
print(Z)


[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [122]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [125]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [69]:
Z = np.random.random(10)
for i in range(5):
   np.put(Z, np.random.randint(10), v=0)
Z

answer(57)


n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [80]:
Z = np.random.random((5,5))
print(Z)
hint(58)
M = np.mean(Z, axis=1, keepdims=True)
print(M)
R=Z-M
print(R)
answer(58)

[[0.96626395 0.9417422  0.62097613 0.09466862 0.64337931]
 [0.30540644 0.28247966 0.74233482 0.41153639 0.22892218]
 [0.25030831 0.412729   0.02300411 0.42209532 0.55107595]
 [0.9321074  0.21822174 0.75621002 0.49505614 0.33122181]
 [0.80732759 0.46027062 0.88541304 0.09412209 0.44009103]]
hint: mean(axis=,keepdims=)
[[0.65340604]
 [0.3941359 ]
 [0.33184254]
 [0.54656342]
 [0.53744488]]
[[ 0.3128579   0.28833616 -0.03242991 -0.55873742 -0.01002673]
 [-0.08872946 -0.11165624  0.34819892  0.01740049 -0.16521372]
 [-0.08153423  0.08088646 -0.30883843  0.09025278  0.21923341]
 [ 0.38554398 -0.32834168  0.20964659 -0.05150728 -0.21534161]
 [ 0.26988272 -0.07717426  0.34796817 -0.44332278 -0.09735384]]
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)


#### 59. How to sort an array by the nth column? (★★☆)

In [70]:
Z = np.random.randint(0,20,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])


[[12  7  1]
 [10 19 19]
 [17  3 10]]
[[17  3 10]
 [12  7  1]
 [10 19 19]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [80]:
Z = np.random.randint(1,15, (3,3))
Z[:,2]=0
print(Z)
# answer(60)
print(Z.any(axis=0))
print(~Z.any(axis=0))

print((~Z.any(axis=0)).any())


[[12 11  0]
 [ 6  5  0]
 [ 6  1  0]]
[ True  True False]
[False False  True]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [83]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.44359320876976693


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [86]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [89]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [60]:
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)
print(I)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 7 7 3 4 5 1 2 6 7 5 6 7 1 6 4 6 7 8 3]
[2. 3. 2. 3. 3. 3. 5. 6. 2. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [68]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)


[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [73]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)


64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [86]:
Z = np.random.randint(0, 2, size=16).reshape((2,2,2,2))
print(Z)
S = np.sum(Z, axis=(-1,-2))
print(S)

[[[[0 0]
   [1 1]]

  [[1 0]
   [0 1]]]


 [[[0 1]
   [1 1]]

  [[0 1]
   [1 1]]]]
[[2 2]
 [3 3]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [90]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
#import pandas as pd
#print(pd.Series(D).groupby(S).mean())

# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


#### 69. How to get the diagonal of a dot product? (★★★)

In [94]:
A = np.random.randint(0, 10, size=(3,3))
B = np.random.randint(0, 10, size=(3,3))
np.diag(np.dot(A, B))

array([55, 26, 22])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [99]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [103]:
A = np.random.random((5,5,3))
B = np.random.random((5,5))
A*B[:,:,None]
# np.dot(A,B[:,:,None])
answer(71)

A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])


#### 72. How to swap two rows of an array? (★★★)

In [62]:
# Z = np.random.random((5,5))
# print(Z)
# a = np.copy(Z[1, :])
# Z[1,:] = Z[2,:]
# Z[2,:]=a
# print(Z)

# answer(72)

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
# print(A[[0,1]])
# print(A[[1,0]])


[[5 6 7 8 9]
 [0 1 2 3 4]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [64]:
faces = np.random.randint(0,100,(10,3))
print(faces)
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[[42 22 38]
 [68 37 72]
 [93 41 63]
 [73  7 57]
 [94 72 68]
 [72 51 14]
 [10 76 88]
 [ 7 97 55]
 [69 74 57]
 [69 24 97]]
[( 7, 55) ( 7, 57) ( 7, 73) ( 7, 97) (10, 76) (10, 88) (14, 51) (14, 72)
 (22, 38) (22, 42) (24, 69) (24, 97) (37, 68) (37, 72) (38, 42) (41, 63)
 (41, 93) (51, 72) (55, 97) (57, 69) (57, 73) (57, 74) (63, 93) (68, 72)
 (68, 94) (69, 74) (69, 97) (72, 94) (76, 88)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [68]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

answer(77)


# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)